### Create a user
POST http://localhost:3000/api/v1/register
Accept: application/json
Content-Type: application/json

{
  "name": "Hanif Al Irsyad",
  "email": "bensatriya3@gmail.com",
  "nim": "2024",
  "password": "12345678"
}

### VALIDATE OTP
POST http://localhost:3000/api/v1/otp/validate
Accept: application/json
Content-Type: application/json

{
  "ref_code":"hqtghkmgxz78424",
  "otp_value":"223426"
}

### SEND OTP EMAIL
POST http://localhost:3000/api/v1/otp/send
Accept: application/json
Content-Type: application/json

{
  "ref_code":"lkfoqjipld97803"
}

### CREATE USER
POST http://localhost:3000/api/v1/users
Accept: application/json
Content-Type: application/json

{
  "email": "bene@gmail.com",
  "nim": "20.11.3785",
  "name": "bene",
  "username": "beneboba",
  "bio": "cobadeng",
  "password": "apaya"
}

