### Create a user
POST http://localhost:3000/api/v1/register
Accept: application/json
Content-Type: application/json

{
  "name": "Hanif Al Irsyad",
  "email": "coba@amikompedia.com",
  "nim": "2024",
  "password": "12345678"
}

###
POST http://localhost:3000/api/v1/otp
Accept: application/json
Content-Type: application/json

{
  "ref_code":"hqtghkmgxz78424",
  "otp_value":"223426"
}